In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


In [6]:
# add an r as we are reading it as raw string or else add '\' before every partition of the path
df = pd.read_csv(r"D:\Sem - 5\ML- LAB\Assg-1 - KNN\fruit_dataset.csv")

# print(df.head())

x = df.iloc[ : , 2: ] # all input features
y = df.iloc[ : , 0:1] # class labels

x_train, x_test, y_train, y_test = train_test_split(x,y,random_state = 1234, test_size = 0.25, shuffle = True)

In [48]:
def knn(x_train, x_test_sample, k, y_train):
    x_test_sample = np.array(x_test_sample)
    distances = []
    for i in range(len(x_train)):
        x_train_sample = np.array(x_train.iloc[i])
        label = y_train.iloc[i, 0]
        dist = 0
        for j in range(len(x_train_sample)):
            dist += (x_train_sample[j] - x_test_sample[j])**2
        dist = dist**0.5
        distances.append((dist, label))
    
    distances.sort(key = lambda x:x[0])

    k_nearest_labels = [label for _,label in distances[ : k]]
     
    return k_nearest_labels

In [49]:
def fun(k_nearest_labels, x_test_sample, x_train, y_train, k):
    # most common label
    k_nearest_labels = knn(x_train, x_test_sample, k, y_train)
    label_counts = {}
    for label in k_nearest_labels:
        if label in label_counts:
            label_counts[label] += 1
        else:
            label_counts[label] = 1
    
    print(label_counts)
    
    most_common_label = None
    max_count = 0
    for label, count in label_counts.items():
        if count >= max_count:
            max_count = count
            most_common_label = label
    return most_common_label

In [55]:
k = 5
tc = len(x_test)
tcor = 0
for ind in range(len(x_test)):
    x_test_sample = np.array(x_test.iloc[ind])
    ("X_test_sample : ")
    print(x_test_sample)
    knns = knn(x_train, x_test_sample, k, y_train)
    predicted_label = fun(knns, x_test_sample, x_train, y_train, k)
    actual_label = y_test.iloc[ind, 0]
    print("Actual Label : ", actual_label)
    print("Predicted Label : ", predicted_label)
    if actual_label == predicted_label:
        tcor += 1
    print('-----------------------------------------------------')

acc = tcor / tc

print(f"Accuracy of the model is : {acc*100 : .4f}")

[160.     7.     7.4    0.81]
{3: 3, 1: 2}
Actual Label :  3
Predicted Label :  3
-----------------------------------------------------
[200.     7.3   10.5    0.72]
{4: 3, 3: 1, 1: 1}
Actual Label :  4
Predicted Label :  4
-----------------------------------------------------
[178.     7.1    7.8    0.92]
{3: 1, 1: 4}
Actual Label :  1
Predicted Label :  1
-----------------------------------------------------
[140.     7.3    7.1    0.87]
{3: 3, 4: 2}
Actual Label :  1
Predicted Label :  3
-----------------------------------------------------
[80.    5.9   4.3   0.81]
{2: 3, 4: 2}
Actual Label :  2
Predicted Label :  2
-----------------------------------------------------
[116.     6.     7.5    0.72]
{4: 5}
Actual Label :  4
Predicted Label :  4
-----------------------------------------------------
[144.     6.8    7.4    0.75]
{3: 3, 1: 1, 4: 1}
Actual Label :  3
Predicted Label :  3
-----------------------------------------------------
[164.    7.3   7.7   0.7]
{3: 2, 1: 3}
Actual 